sudo: required
services:
  - docker
language: elixir
elixir:
  - 1.3.4
otp_release:
  - 19.0
env:
  - MIX_ENV=test
script:
  - mix test
after_script:
  - mix coveralls.travis
  - mix credo
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report

